version: 2 
jobs: 
  build: 
    docker: 
      - image: circleci/golang:1.8 
    working_directory: /go/src/github.com/integr8ly/managed-service-broker

    steps:
      - checkout 
      - setup_remote_docker
      - run: make build_binary
      - run: ./scripts/docker_build_and_push.sh
    
