apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: managedservicenamespaces.integreatly.org
spec:
  group: integreatly.org
  names:
    kind: ManagedServiceNamespace
    listKind: ManagedServiceNamespaceList
    plural: managedservicenamespaces
    singular: managedservicenamespace
  scope: Namespaced
  version: v1alpha1
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          description: Spec for a ManagedServiceNamespace
          required:
          - consumerNamespaces
          - userId
          properties:
            userId:
              type: string
              description: This User will be granted view access to the ManagedServiceNamespace and update access to the Integration resource.
            consumerNamespaces:
              type: array
              description: Names of the namespaces that will be allowed use the services created in ManagedServiceNamespace.